<?php $this->headStyle()->appendStyle('
.result {
    margin: 2em 0;
    height: 300px;
    padding-right: 1em;
}
.result p.location {
    margin: .3em 0;
    font-size: 9pt;
}
.result h2 {
    margin: 0;
    font-size: 18pt;
}
.result p.description {
    margin: .3em 0;
    max-height: 150px;
    overflow: auto;
    padding-right: .5em;
}
.result p.link {
    font-size: 9pt;
}
') ?>

<div class="container">

    <p style="margin-top: 3em;">
        <?php echo count($hits); ?> Projekte der Elektromobilität
    </p>

    <hr>

    <div class="row">
    <?php foreach ($hits as $hit): ?>
        <div class="col-md-5">
            <div class="result">
                <p class="location">
                    <?php echo $this->escapeHtml($hit->country); ?>
                </p>
                <h2>
                    <a href="<?php echo $this->escapeHtml($hit->url); ?>">
                    <?php echo $this->escapeHtml($hit->title); ?></a>
                </h2>
                <p class="description">
                    <?php echo $this->escapeHtml($hit->description); ?>
                </p>
                <p class="link">
                    <a href="<?php echo $this->escapeHtml($hit->url); ?>">
                        <?php echo $this->escapeHtml(parse_url($hit->url, PHP_URL_HOST)); ?></a>
                </p>
            </div>
        </div>
    <?php endforeach; ?>
    </div>
</div>