<?php $this->headStyle()->appendStyle('
.result, form {
    max-width: 700px;
    margin: 2em 0;
}
.result p.location {
    margin: .3em 0;
    font-size: 9pt;
}
.result h2 {
    margin: 0;
    font-size: 18pt;
}
.result p.description {
    margin: .3em 0;
}
.result p.link {
    font-size: 9pt;
}
') ?>

<div class="container">
    <form action="<?php echo $this->url('search'); ?>" method="get" class="form-inline" role="form">
        <div class="input-group">
            <input type="text" name="q" class="form-control" id="searchTerm" placeholder="Suchbegriff" value="<?php echo $this->escapeHtml($this->q); ?>">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-default">Suchen</button>
            </span>
        </div>
    </form>

    <p>Diese Suche ergab <?php echo count($hits); ?> Treffer.</p>

    <?php foreach ($hits as $hit) : ?>

    <div class="result">
        <p class="location">
            <?php echo $this->escapeHtml($hit->country); ?>,
            <?php echo $this->escapeHtml(parse_url($hit->url, PHP_URL_HOST)); ?>
        </p>
        <h2>
            <a href="<?php echo $this->escapeHtml($hit->url); ?>">
            <?php echo $this->escapeHtml($hit->title); ?></a>
        </h2>
        <p class="description">
            <?php echo $this->escapeHtml($hit->description); ?>
        </p>
        <p class="link">
            <a href="<?php echo $this->escapeHtml($hit->url); ?>"><?php echo $this->escapeHtml($hit->url); ?></a>
        </p>
    </div>

    <?php endforeach; ?>
</div>