<div class="jumbotron">
    <h1>Schaufensters Elektromobilität</h1>
    <p>
        Diese Seite bietet eine Suchmaschine für die Projekte des
        <a href="http://www.schaufenster-elektromobilitaet.org/programm/">Schaufensters Elektromobilität</a>.
        Dursucht werden die Projektseiten, inklusive Projekttitel, Kurzbeschreibung, Zielen etc.
    </p>
    <p>&nbsp;</p>
    <p>
        <form action="<?php echo $this->url('search'); ?>" method="get" class="form-inline" role="form">
            <div class="input-group">
                <input type="text" name="q" class="form-control input-lg" id="searchTerm" placeholder="Suchbegriff">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default input-lg">Suchen</button>
                </span>
            </div>
        </form>
    </p>
</div>
